//  External Dependencies
import Head from "next/head";
import React, { FC, PropsWithChildren } from "react";

//  Internal Dependencies
import Navbar from "./Navbar";

const Layout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Insite AI HomeTask</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <div>{children}</div>
      </>
    </>
  );
};

export default Layout;
